apiVersion: v1
kind: Service
metadata:
  name: console-frontend-service
  namespace: lion
  labels:
    app: console-frontend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: console-frontend
      targetPort: 80
  selector:
    app: console-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-frontend
  namespace: lion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-frontend
  template:
    metadata:
      namespace: console-frontend
      labels:
        app: console-frontend
    spec:
      containers:
        - name: console-frontend
          image: lion/console-frontend:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "300Mi"
              cpu: "2000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3