apiVersion: v1
kind: Service
metadata:
  namespace: lion
  name: nacos-headless
  labels:
    app: nacos-headless
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 7848
      name: rpc
      targetPort: 7848
  clusterIP: None
  selector:
    app: nacos
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: lion
  name: nacos
  labels:
    app: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      namespace: lion
      name: nacos
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          imagePullPolicy: IfNotPresent
          image: nacos/nacos-server:1.3.2
          resources:
            limits:
              memory: "768Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 7848
              name: rpc
          env:
            - name: JVM_XMS
              value: 512m
            - name: JVM_XMX
              value: 512m
            - name: JVM_XMN
              value: 256m
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_HOST
              value: 10.90.247.226
            - name: MYSQL_SERVICE_DB_NAME
              value: nacos_1_3_2
            - name: MYSQL_SERVICE_PORT
              value: "3306"
            - name: MYSQL_SERVICE_USER
              value: root
            - name: MYSQL_SERVICE_PASSWORD
              value: root
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.lion.svc.cluster.local:8848 nacos-1.nacos-headless.lion.svc.cluster.local:8848 nacos-2.nacos-headless.lion.svc.cluster.local:8848"
          volumeMounts:
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: managed-nfs-storage
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: logdir
      spec:
        storageClassName: managed-nfs-storage
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
#---
#apiVersion: v1
#kind: Service
#metadata:
#  namespace: lion
#  name: nacos-service
#spec:
#  type: ClusterIP
#  selector:
#    app: nacos
#  ports:
#    - port: 8848
#      protocol: TCP
#      targetPort: 8848
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: lion
  name: nacos-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.lion-nacos.com
      http:
        paths:
          - path: /nacos
            backend:
              serviceName: nacos-headless
              servicePort: 8848