apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: lion
  name: lion-gateway-ingress
  annotations:
    nginx.org/server-snippets: |
      location /api {
        proxy_redirect off;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        REMOTE-HOST $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite /api/(.*)$ /$1 break;
        proxy_pass http://lion-gateway-service.lion.svc.cluster.local:8080;
      }
      location /api/file {
        proxy_redirect off;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        REMOTE-HOST $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        rewrite /api/file/(.*)$ /$1 break;
        proxy_pass http://minio-headless.lion.svc.cluster.local:9000;
      }
spec:
  ingressClassName: nginx
  rules:
    - host: www.lion.com
      http:
        paths:
          - backend:
              serviceName: console-frontend
              servicePort: 80