#该service用于k8s集群内部访问外部mysql
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: lion
spec:
  ports:
    - port: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: lion
subsets:
  - addresses:
      - ip: 172.16.30.1
    ports:
      - port: 3306